Added error types for each case for the status code
sujrd/storekit_ruby pull request #1
Opened 2017-03-07 15:35 UTC by majioa

2017-03-07 23:35 UTC, dteoh requested changes
Thank you for your PR. I have left you some comments.

2017-03-07 23:35 UTC, dteoh commented on lib/storekit/error.rb
> +      case status_code
Can you follow the indentation style and case statement style in the `initialize` method?

2017-03-07 23:35 UTC, dteoh commented on lib/storekit/error.rb
> +      @status_code = status_code
This is not needed because it is being set in `initialize`.

2017-03-07 23:35 UTC, dteoh commented on lib/storekit/error.rb
> +      type.is_a?(NilClass) && super || type.new(status_code)
Add some new unit tests for this and at least one of the error subclass branches in the case statement.

2017-03-07 23:35 UTC, dteoh commented on lib/storekit/error.rb
> +  class SharedSecretInvalidError < ValidationError; end
Since the first two new error classes have the `Invalid` prefix, let's do the same for this one as well.

2017-03-08 09:07 UTC, majioa commented
Fixed some.

2017-03-08 23:41 UTC, dteoh approved these changes

2017-03-08 23:44 UTC, merged

2017-03-08 23:44 UTC, dteoh commented
Thanks